services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: assistant
      POSTGRES_DB: assistant
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - support_agent

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant_db
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - support_agent

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - ./data/open-webui:/app/backend/data
    networks:
      - support_agent

  temporal:
    container_name: temporal
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: assistant
      POSTGRES_PWD: assistant
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/docker-temporal-development.sql
    image: temporalio/auto-setup:1.25.2
    restart: unless-stopped
    ports:
      - 7233:7233
    volumes:
      - ./config/docker-temporal-development.sql:/etc/temporal/config/dynamicconfig/docker-temporal-development.sql
    networks:
      - support_agent

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.25.2-tctl-1.18.1-cli-1.1.1
    stdin_open: true
    tty: true
    networks:
      - support_agent

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: "temporal:7233"
      TEMPORAL_CORS_ORIGINS: "http://localhost:3000"
    image: temporalio/ui:2.31.2
    restart: unless-stopped
    ports:
      - 8888:8080
    networks:
      - support_agent

networks:
  support_agent:
    name: support_agent
    driver: bridge