version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: assistant
      POSTGRES_DB: assistant
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

