services:
  temporal:
    container_name: temporal
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: assistant
      POSTGRES_PWD: assistant
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/docker-temporal-development.sql
    image: temporalio/auto-setup:1.25.2
    restart: unless-stopped
    ports:
      - 7233:7233
    volumes:
      - ./config/docker-temporal-development.sql:/etc/temporal/config/dynamicconfig/docker-temporal-development.sql
    networks:
      - support_agent

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.25.2-tctl-1.18.1-cli-1.1.1
    stdin_open: true
    tty: true
    networks:
      - support_agent

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: "temporal:7233"
      TEMPORAL_CORS_ORIGINS: "http://localhost:3000"
    image: temporalio/ui:2.31.2
    restart: unless-stopped
    ports:
      - 8888:8080
    networks:
      - support_agent

networks:
  support_agent:
    name: support_agent
    external: true