
###
POST http://localhost:8080/ai/assistant/1
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": "can you please tell me a 2000 word essay?"
}

###
POST http://localhost:8080/ai/assistant/1
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": "Schedule meeting with Details to watch movie : \n Title - Group Discussion - 2025-06-28T05:19:41Z \n Duration - 30 minutes \n Participants Ira"

}

###
POST http://localhost:8080/ai/assistant/1
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": " cancel Meeting with Ira"
}

###
POST http://localhost:8080/ai/assistant/3
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": "please suggest some Drama movies to watch with team"
}




###
POST http://localhost:8080/ai/assistant/1
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": "can you please cancel meeting with Ram"
}


###
POST http://localhost:8080/ai/assistant/1
Content-Type: application/json

{
  "userId": "e85c20f0-ad28-4531-9ac4-158b9b4a3ece",
  "question": "cancel meeting with id ae7654e3-8f10-4f86-93b9-bbd2376e350d"
}
