management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      access: read-only


server:
  port: 8081
# Using spring-ai-starter-mcp-server-webmvc
spring:
  ai:
    mcp:
      server:
        name: support-mcp-server
        protocol: stateless
        version: 1.0.0
        type: SYNC
        instructions: "This server provides support ticket creation tools and resources"

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
