server:
  port: 8082
spring:
  threads:
    virtual:
      enabled: true
  jackson:
  jpa:
    hibernate:
      ddl-auto: create
  data:
      repositories:
        enabled: true
        bootstrap-mode: default
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 10m
        max-retries: 2
      embedding:
        model: dengcao/Qwen3-Embedding-8B:Q8_0
        options:
          temperature: 0.1
      chat:
        model: qwen3:8b
        options:
          temperature: 0.1
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: support
        use-tls: false
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: assistant
    password: assistant
  temporal:
    namespace: default
    connection:
      target: localhost:7233
    workers-auto-discovery:
      packages: com.jinternals.support.agent.etl

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
