spring:
    main:
      web-application-type: none
    ai:
      openai:
        api-key: "na"
        base-url: "http://localhost:12434/engines"
        chat:
          options:
            model: ai/qwen3:8B-Q4_K_M
        embedding:
          options:
            model: ai/mxbai-embed-large:latest
      vectorstore:
        qdrant:
          host: localhost
          port: 6334
          collection-name: support
          use-tls: false
          initialize-schema: true

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
