spring:
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: assistant
    password: assistant

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
