spring:
  threads:
    virtual:
      enabled: true
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 10m
        max-retries: 2
      embedding:
        model: dengcao/Qwen3-Embedding-8B:Q8_0
      chat:
        model: qwen3:8b
        options:
          temperature: 0.1
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: support
        use-tls: false
        initialize-schema: true
    mcp:
      client:
        enabled: true
        version: 1.0.0
        name: support-mcp-server
        type: sync
        sse:
          connections:
            supportMcpServer:
              url: http://localhost:8081
              sse-endpoint: /sse
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: assistant
    password: assistant

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
