spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: ${OPEN_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4


    #    ollama:
#      embedding:
#        model: mxbai-embed-large
#      chat:
#        model: llama3.2
#      base-url: http://localhost:11434
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8081
              sse-endpoint: /sse
        enabled: true
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: assistant
    password: assistant

logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol: DEBUG
